# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'youMed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for youMed
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireObjectMapper', :git => 'https://github.com/RomanPodymov/AlamofireObjectMapper.git', :branch => 'xcode-10-2-fix'
    pod 'JGProgressHUD'
    pod 'RealmSwift'
    pod 'SDWebImage'
    pod 'FSCalendar'
    pod 'iOSDropDown'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'CalendarKit'

  target 'youMedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'youMedUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5.0'
                config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
            end
        end
    end

end
